# This is a guide to get you started quickly and generate your API metadata.
# Be aware that YAML has indentation based scoping.
# Auto-suggestion support is available:
  # for field suggestion press Alt-Space
  # for value suggestion press a-Space
  # if you have a specific field/value in mind, start typing for available options.
swagger: '2.0'

# This is your API metadata

# insert 'info' block to add general information about your API




# insert 'paths' block to add metadata about your paths endpoints